Add methods for get or update instantiate_model
networktocode/diffsync pull request #182
Opened 2022-11-05 02:15 UTC by itdependsnetworks

2022-11-05 11:11 UTC, itdependsnetworks commented
Doh’, this doesn’t make sense. When I went to use this, I realized the method was conditionally adding. This is just redundant

2022-11-05 18:23 UTC, itdependsnetworks commented
Double Doh'!! ok, red herring, there was an issue, I didn't see where the code was actually issuing a `self.add` (it was nested more), so I thought it was adding.... it was :)

2022-11-07 09:30 UTC, Kircheneer requested changes

2022-11-07 09:30 UTC, Kircheneer commented on diffsync/store/__init__.py
> +    def get_or_instantiate_model(self, obj: "DiffSyncModel") -> Tuple["DiffSyncModel", bool]:
Maybe this should be called `get_or_add_model_instance`, seeing as
- the model class instance is already instantiated
- the model itself is already known to the `DiffSync` instance at this point (i.e. we aren't "adding" a model)
- "`get_or_add`" also accurately reflects the methods called against `self`

2022-11-07 09:30 UTC, Kircheneer commented on diffsync/store/__init__.py
> +            Provides the existing or new object and whether it was created or not.
This needs to be updated to reflect the functionality (created vs. instantiated vs. added).

2022-11-07 09:30 UTC, Kircheneer commented on diffsync/store/__init__.py
> +        """
See comments for current `get_or_instantiate_model` method

2022-11-07 09:30 UTC, Kircheneer commented on diffsync/store/__init__.py
> +            # Add the object to diffsync adapter
I believe the concept of an adapter is something that the SSoT framework uses, but it is never mentioned in this repository. Possibly:
`# Add the object to the diffsync instance`?

2022-11-07 09:30 UTC, Kircheneer commented on diffsync/store/__init__.py
> +            if getattr(obj, attr) != value:
I believe we can omit this check to make it simpler. Just `setattr` always, if its the same the outcome is also the same.

2022-11-23 08:03 UTC, Kircheneer commented on diffsync/store/__init__.py
> +            instance: An instance of the DiffSyncModel to update or create.
```suggestion
            instance: An instance of the DiffSyncModel to update or add.
```

2022-11-24 18:02 UTC, chadell approved these changes
LGTM

2022-11-28 12:24 UTC, Kircheneer approved these changes

2022-11-28 12:24 UTC, merged